/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    'payload-mcp-api-keys': PayloadMcpApiKeyAuthOperations;
  };
  blocks: {};
  collections: {
    announcements: Announcement;
    sites: Site;
    'site-blueprints': SiteBlueprint;
    categories: Category;
    pages: Page;
    redirects: Redirect;
    'social-platforms': SocialPlatform;
    'social-accounts': SocialAccount;
    media: Media;
    keywords: Keyword;
    'content-briefs': ContentBrief;
    'serp-snapshots': SerpSnapshot;
    authors: Author;
    articles: Article;
    rankings: Ranking;
    'workflow-jobs': WorkflowJob;
    'site-quotas': SiteQuota;
    'affiliate-networks': AffiliateNetwork;
    offers: Offer;
    'click-events': ClickEvent;
    commissions: Commission;
    users: User;
    'knowledge-base': KnowledgeBase;
    'audit-logs': AuditLog;
    tenants: Tenant;
    'original-evidence': OriginalEvidence;
    'landing-templates': LandingTemplate;
    'page-link-graph': PageLinkGraph;
    'plugin-ai-instructions': PluginAiInstruction;
    'automation-triggers': AutomationTrigger;
    'automation-steps': AutomationStep;
    workflows: Workflow;
    'workflow-runs': WorkflowRun;
    'payload-mcp-api-keys': PayloadMcpApiKey;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    announcements: AnnouncementsSelect<false> | AnnouncementsSelect<true>;
    sites: SitesSelect<false> | SitesSelect<true>;
    'site-blueprints': SiteBlueprintsSelect<false> | SiteBlueprintsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    'social-platforms': SocialPlatformsSelect<false> | SocialPlatformsSelect<true>;
    'social-accounts': SocialAccountsSelect<false> | SocialAccountsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    keywords: KeywordsSelect<false> | KeywordsSelect<true>;
    'content-briefs': ContentBriefsSelect<false> | ContentBriefsSelect<true>;
    'serp-snapshots': SerpSnapshotsSelect<false> | SerpSnapshotsSelect<true>;
    authors: AuthorsSelect<false> | AuthorsSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    rankings: RankingsSelect<false> | RankingsSelect<true>;
    'workflow-jobs': WorkflowJobsSelect<false> | WorkflowJobsSelect<true>;
    'site-quotas': SiteQuotasSelect<false> | SiteQuotasSelect<true>;
    'affiliate-networks': AffiliateNetworksSelect<false> | AffiliateNetworksSelect<true>;
    offers: OffersSelect<false> | OffersSelect<true>;
    'click-events': ClickEventsSelect<false> | ClickEventsSelect<true>;
    commissions: CommissionsSelect<false> | CommissionsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'knowledge-base': KnowledgeBaseSelect<false> | KnowledgeBaseSelect<true>;
    'audit-logs': AuditLogsSelect<false> | AuditLogsSelect<true>;
    tenants: TenantsSelect<false> | TenantsSelect<true>;
    'original-evidence': OriginalEvidenceSelect<false> | OriginalEvidenceSelect<true>;
    'landing-templates': LandingTemplatesSelect<false> | LandingTemplatesSelect<true>;
    'page-link-graph': PageLinkGraphSelect<false> | PageLinkGraphSelect<true>;
    'plugin-ai-instructions': PluginAiInstructionsSelect<false> | PluginAiInstructionsSelect<true>;
    'automation-triggers': AutomationTriggersSelect<false> | AutomationTriggersSelect<true>;
    'automation-steps': AutomationStepsSelect<false> | AutomationStepsSelect<true>;
    workflows: WorkflowsSelect<false> | WorkflowsSelect<true>;
    'workflow-runs': WorkflowRunsSelect<false> | WorkflowRunsSelect<true>;
    'payload-mcp-api-keys': PayloadMcpApiKeysSelect<false> | PayloadMcpApiKeysSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'commission-rules': CommissionRule;
    'public-landing': PublicLanding;
    'quota-rules': QuotaRule;
    'admin-branding': AdminBranding;
    'llm-prompts': LlmPrompt;
    'prompt-library': PromptLibrary;
    'pipeline-settings': PipelineSetting;
  };
  globalsSelect: {
    'commission-rules': CommissionRulesSelect<false> | CommissionRulesSelect<true>;
    'public-landing': PublicLandingSelect<false> | PublicLandingSelect<true>;
    'quota-rules': QuotaRulesSelect<false> | QuotaRulesSelect<true>;
    'admin-branding': AdminBrandingSelect<false> | AdminBrandingSelect<true>;
    'llm-prompts': LlmPromptsSelect<false> | LlmPromptsSelect<true>;
    'prompt-library': PromptLibrarySelect<false> | PromptLibrarySelect<true>;
    'pipeline-settings': PipelineSettingsSelect<false> | PipelineSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User | PayloadMcpApiKey;
  jobs: {
    tasks: {
      'http-request-step': TaskHttpRequestStep;
      'create-document': TaskCreateDocument;
      'read-document': TaskReadDocument;
      'update-document': TaskUpdateDocument;
      'delete-document': TaskDeleteDocument;
      'send-email': TaskSendEmail;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface PayloadMcpApiKeyAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * 系统公告（租户内广播）与团队公告（组长发布给本组）。
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "announcements".
 */
export interface Announcement {
  id: number;
  tenant?: (number | null) | Tenant;
  /**
   * 组长仅可创建「团队公告」。系统公告仅超级管理员可发布。
   */
  kind: 'system' | 'team';
  /**
   * 团队公告面向该组长及其组员（users.teamLead 指向此用户）。
   */
  teamLead?: (number | null) | User;
  /**
   * 创建者（自动填充）。
   */
  author?: (number | null) | User;
  title: string;
  body: string;
  isActive?: boolean | null;
  /**
   * 置顶显示（前端可按需排序）。
   */
  isPinned?: boolean | null;
  startsAt?: string | null;
  endsAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants".
 */
export interface Tenant {
  id: number;
  name: string;
  slug: string;
  domain: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Optional team lead for commission / reporting (same tenant; refine access in PRD as needed).
   */
  teamLead?: (number | null) | User;
  /**
   * Super Admin：全租户。仅 Super Admin 可修改本字段。其它角色（财务 / 运营 / 组长 / 站长）的具体权限在代码与各集合 access 中逐步收紧。
   */
  roles: ('user' | 'super-admin' | 'finance' | 'ops-manager' | 'team-lead' | 'site-manager')[];
  tenants?:
    | {
        tenant: number | Tenant;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sites".
 */
export interface Site {
  id: number;
  tenant?: (number | null) | Tenant;
  name: string;
  /**
   * URL-safe key; pair with tenant for uniqueness in your workflows.
   */
  slug: string;
  primaryDomain: string;
  status: 'draft' | 'active' | 'archived';
  /**
   * Optional layout/template blueprint for this site.
   */
  blueprint?: (number | null) | SiteBlueprint;
  /**
   * 公开首页预设主题与配文；换模版仅在此处。设计里可微调字体/配色/文案。
   */
  landingTemplate?: (number | null) | LandingTemplate;
  /**
   * Users who operate this site (optional; tenant scoping still applies).
   */
  operators?: (number | User)[] | null;
  notes?: string | null;
  /**
   * 留空则使用全局兜底或站点名称。
   */
  landingBrowserTitle?: string | null;
  landingSiteName?: string | null;
  landingTagline?: string | null;
  landingLoggedInTitle?: string | null;
  landingLoggedInSubtitle?: string | null;
  landingFooterLine?: string | null;
  landingCtaLabel?: string | null;
  landingBgColor?: string | null;
  landingTextColor?: string | null;
  landingMutedColor?: string | null;
  landingCtaBgColor?: string | null;
  landingCtaTextColor?: string | null;
  landingFontPreset?: ('' | 'system' | 'serif' | 'noto_sans_sc') | null;
  landingBlogPrimaryColor?: string | null;
  landingBlogAccentColor?: string | null;
  landingBlogContentBgColor?: string | null;
  landingBlogCardBgColor?: string | null;
  landingBlogHeaderTextColor?: string | null;
  landingBlogHeadingColor?: string | null;
  landingBlogBodyColor?: string | null;
  landingAboutTitle?: string | null;
  landingAboutBio?: string | null;
  landingAboutImage?: (number | null) | Media;
  landingAboutCtaLabel?: string | null;
  landingAboutCtaHref?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-blueprints".
 */
export interface SiteBlueprint {
  id: number;
  tenant?: (number | null) | Tenant;
  name: string;
  slug: string;
  /**
   * 新建必填；旧数据可暂为空后再补全。
   */
  site?: (number | null) | Site;
  description?: string | null;
  /**
   * Arbitrary JSON for themes, sections, or generator defaults.
   */
  templateConfig?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  designBrowserTitle?: string | null;
  designSiteName?: string | null;
  designTagline?: string | null;
  designLoggedInTitle?: string | null;
  designLoggedInSubtitle?: string | null;
  designFooterLine?: string | null;
  designCtaLabel?: string | null;
  designBgColor?: string | null;
  designTextColor?: string | null;
  designMutedColor?: string | null;
  designCtaBgColor?: string | null;
  designCtaTextColor?: string | null;
  designFontPreset?: ('' | 'system' | 'serif' | 'noto_sans_sc') | null;
  designBlogPrimaryColor?: string | null;
  designBlogAccentColor?: string | null;
  designBlogContentBgColor?: string | null;
  designBlogCardBgColor?: string | null;
  designBlogHeaderTextColor?: string | null;
  designBlogHeadingColor?: string | null;
  designBlogBodyColor?: string | null;
  designAboutTitle?: string | null;
  designAboutBio?: string | null;
  designAboutImage?: (number | null) | Media;
  designAboutCtaLabel?: string | null;
  designAboutCtaHref?: string | null;
  /**
   * Lexical or JSON template for /about, /affiliate-disclosure, etc.
   */
  trustAssetsTemplate?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  mainNavTemplate?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  footerTemplate?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  showBreadcrumb?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  tenant?: (number | null) | Tenant;
  alt: string;
  /**
   * 新建必填；旧数据可暂为空后再补全。
   */
  site?: (number | null) | Site;
  assetClass?: ('decorative' | 'evidence') | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
}
/**
 * 站点前台预设主题与配文；在「设计」中可微调。
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "landing-templates".
 */
export interface LandingTemplate {
  id: number;
  tenant?: (number | null) | Tenant;
  name: string;
  /**
   * URL-safe key; unique per tenant with `slug`.
   */
  slug: string;
  description?: string | null;
  /**
   * 完整可访问的前台 URL，且对应站点须已选用本模版（本地示例：http://localhost:3000/zh/?site=站点 slug）。
   */
  previewUrl?: string | null;
  /**
   * 留空则使用站点名称或全局兜底。
   */
  landingBrowserTitle?: string | null;
  landingSiteName?: string | null;
  landingTagline?: string | null;
  landingLoggedInTitle?: string | null;
  landingLoggedInSubtitle?: string | null;
  landingFooterLine?: string | null;
  landingCtaLabel?: string | null;
  landingBgColor?: string | null;
  landingTextColor?: string | null;
  landingMutedColor?: string | null;
  landingCtaBgColor?: string | null;
  landingCtaTextColor?: string | null;
  landingFontPreset?: ('' | 'system' | 'serif' | 'noto_sans_sc') | null;
  /**
   * CSS 颜色，如 #2d8659
   */
  blogPrimaryColor?: string | null;
  /**
   * 如 #e6c84a
   */
  blogAccentColor?: string | null;
  /**
   * 如 #f0f0f0
   */
  blogContentBgColor?: string | null;
  /**
   * 如 #ffffff
   */
  blogCardBgColor?: string | null;
  /**
   * 如 #ffffff
   */
  blogHeaderTextColor?: string | null;
  /**
   * 如 #333333
   */
  blogHeadingColor?: string | null;
  /**
   * 如 #444444
   */
  blogBodyColor?: string | null;
  aboutTitle?: string | null;
  aboutBio?: string | null;
  aboutImage?: (number | null) | Media;
  aboutCtaLabel?: string | null;
  /**
   * 相对路径如 /pages/about 或绝对 URL
   */
  aboutCtaHref?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  tenant?: (number | null) | Tenant;
  name: string;
  slug: string;
  /**
   * 新建必填；旧数据可暂为空后再补全。
   */
  site?: (number | null) | Site;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  tenant?: (number | null) | Tenant;
  title: string;
  slug?: string | null;
  /**
   * URL prefix /zh/ or /en/; must be unique per site + slug.
   */
  locale: 'zh' | 'en';
  /**
   * Owning site (optional while migrating legacy content).
   */
  site?: (number | null) | Site;
  categories?: (number | Category)[] | null;
  featuredImage?: (number | null) | Media;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  status: 'draft' | 'published' | 'archived';
  publishedAt?: string | null;
  excerpt?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  tenant?: (number | null) | Tenant;
  /**
   * Optional. Leave empty for a host-wide rule; set to scope to one site.
   */
  site?: (number | null) | Site;
  /**
   * Full pathname including locale, e.g. /zh/old-slug or /en/legacy
   */
  fromPath: string;
  /**
   * Target path (relative, e.g. /zh/new) or absolute URL.
   */
  toPath: string;
  statusCode: '301' | '302';
  enabled?: boolean | null;
  /**
   * Lower runs first when multiple rules match (should be unique per fromPath).
   */
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "social-platforms".
 */
export interface SocialPlatform {
  id: number;
  tenant?: (number | null) | Tenant;
  name: string;
  slug: string;
  status: 'active' | 'paused';
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "social-accounts".
 */
export interface SocialAccount {
  id: number;
  tenant?: (number | null) | Tenant;
  platform: number | SocialPlatform;
  site?: (number | null) | Site;
  handle: string;
  status: 'active' | 'disconnected';
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "keywords".
 */
export interface Keyword {
  id: number;
  tenant?: (number | null) | Tenant;
  term: string;
  slug?: string | null;
  /**
   * Optional: scope this keyword to one site.
   */
  site?: (number | null) | Site;
  status: 'draft' | 'active' | 'archived';
  notes?: string | null;
  /**
   * Monthly search volume
   */
  volume?: number | null;
  keywordDifficulty?: number | null;
  cpc?: number | null;
  trend?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  intent?: ('informational' | 'navigational' | 'commercial' | 'transactional') | null;
  geoFriendly?: boolean | null;
  /**
   * Cluster keyword: points to pillar keyword
   */
  pillar?: (number | null) | Keyword;
  serpFeatures?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  lastRefreshedAt?: string | null;
  opportunityScore?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "content-briefs".
 */
export interface ContentBrief {
  id: number;
  tenant?: (number | null) | Tenant;
  title: string;
  primaryKeyword?: (number | null) | Keyword;
  site?: (number | null) | Site;
  intentSummary?: string | null;
  /**
   * Structured sections[] + globalContext (H2/H3, wordBudget, inject)
   */
  outline:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  sources?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  targetWordCount?: number | null;
  competitors?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  peopleAlsoAsk?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  schemaHints?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  status: 'draft' | 'approved' | 'used';
  skillId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "serp-snapshots".
 */
export interface SerpSnapshot {
  id: number;
  tenant?: (number | null) | Tenant;
  searchQuery?: string | null;
  keyword?: (number | null) | Keyword;
  site?: (number | null) | Site;
  engine?: ('google' | 'bing') | null;
  location?: string | null;
  device?: ('desktop' | 'mobile') | null;
  capturedAt: string;
  /**
   * DataForSEO raw (optionally zstd+base64)
   */
  raw?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors".
 */
export interface Author {
  id: number;
  tenant?: (number | null) | Tenant;
  displayName: string;
  slug?: string | null;
  role?: ('editor' | 'reviewer' | 'expert' | 'contributor') | null;
  headshot?: (number | null) | Media;
  bioLexical?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * [{ title, issuer?, year?, verifyUrl? }] — json for simpler D1 migrations
   */
  credentials?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  expertiseAreas?: (number | Category)[] | null;
  /**
   * [{ url }]
   */
  sameAs?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  schemaPersonJsonLd?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  gdprLawfulBasis?: ('consent' | 'legitimate_interest' | 'contract' | 'other' | 'not_applicable') | null;
  gdprRegion?: ('eu' | 'eea' | 'uk' | 'us' | 'other') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  tenant?: (number | null) | Tenant;
  title: string;
  slug?: string | null;
  /**
   * URL prefix /zh/ or /en/; must be unique per site + slug.
   */
  locale: 'zh' | 'en';
  /**
   * Owning site (optional while migrating legacy content).
   */
  site?: (number | null) | Site;
  categories?: (number | Category)[] | null;
  featuredImage?: (number | null) | Media;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  status: 'draft' | 'published' | 'archived';
  publishedAt?: string | null;
  excerpt?: string | null;
  primaryKeyword?: (number | null) | Keyword;
  secondaryKeywords?: (number | Keyword)[] | null;
  contentTemplate?: ('review' | 'comparison' | 'howto' | 'listicle' | 'buyingGuide' | 'pillar') | null;
  qualityScore?: number | null;
  eeatCheck?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  schemaJsonLd?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  vetoCodes?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  featuredOffers?: (number | Offer)[] | null;
  /**
   * Required when status is Published (enforced in hook)
   */
  author?: (number | null) | Author;
  reviewedBy?: (number | null) | Author;
  originalEvidence?: (number | OriginalEvidence)[] | null;
  sourceBrief?: (number | null) | ContentBrief;
  mergedInto?: (number | null) | Article;
  sectionSummaries?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  metaVariants?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  lifecycleStage?:
    | (
        | 'n_a'
        | 'probation'
        | 'winner'
        | 'borderline'
        | 'loser'
        | 'stable_watch'
        | 'repaired'
        | 'dying'
        | 'merged'
        | 'archived'
      )
    | null;
  probationEndsAt?: string | null;
  bestPosition?: number | null;
  currentPosition?: number | null;
  impressions30d?: number | null;
  clicks30d?: number | null;
  nextActionAt?: string | null;
  optimizationHistory?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Populated when body outlink count is in the warn band (see link budget hook).
   */
  linkBudgetWarnings?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  skipLinkBudgetCheck?: boolean | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "offers".
 */
export interface Offer {
  id: number;
  tenant?: (number | null) | Tenant;
  title: string;
  slug?: string | null;
  network: number | AffiliateNetwork;
  /**
   * Sites allowed to promote this offer (optional).
   */
  sites?: (number | Site)[] | null;
  status: 'draft' | 'active' | 'paused';
  externalId?: string | null;
  targetUrl?: string | null;
  commissionNotes?: string | null;
  amazon?: {
    asin?: string | null;
    priceCents?: number | null;
    currency?: string | null;
    ratingAvg?: number | null;
    reviewCount?: number | null;
    imageUrl?: string | null;
    primeEligible?: boolean | null;
    merchantLastSyncedAt?: string | null;
    merchantRaw?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "affiliate-networks".
 */
export interface AffiliateNetwork {
  id: number;
  tenant?: (number | null) | Tenant;
  name: string;
  slug: string;
  websiteUrl?: string | null;
  status: 'active' | 'paused';
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "original-evidence".
 */
export interface OriginalEvidence {
  id: number;
  tenant?: (number | null) | Tenant;
  kind: 'receipt' | 'unboxing' | 'benchmark' | 'hands_on_photo' | 'screenshot' | 'video_frame';
  product?: (number | null) | Offer;
  article?: (number | null) | Article;
  capturedAt?: string | null;
  capturedBy?: (number | null) | User;
  media: number | Media;
  watermarkApplied?: boolean | null;
  exifPreserved?: boolean | null;
  notes?: string | null;
  verifiedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rankings".
 */
export interface Ranking {
  id: number;
  tenant?: (number | null) | Tenant;
  keyword?: (number | null) | Keyword;
  site?: (number | null) | Site;
  searchQuery: string;
  serpPosition?: number | null;
  serpUrl?: string | null;
  capturedAt: string;
  notes?: string | null;
  rawSerp?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  change?: number | null;
  isAiOverviewHit?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "workflow-jobs".
 */
export interface WorkflowJob {
  id: number;
  tenant?: (number | null) | Tenant;
  label: string;
  jobType:
    | 'publish'
    | 'sync'
    | 'ai_generate'
    | 'custom'
    | 'keyword_discover'
    | 'serp_audit'
    | 'brief_generate'
    | 'draft_skeleton'
    | 'draft_section'
    | 'draft_finalize'
    | 'image_generate'
    | 'amazon_sync'
    | 'backlink_scan'
    | 'rank_track'
    | 'alert_eval'
    | 'triage'
    | 'content_audit'
    | 'content_refresh'
    | 'content_merge'
    | 'content_archive'
    | 'meta_ab_optimize'
    | 'internal_link_inject'
    | 'internal_link_rewrite'
    | 'internal_link_reinforce'
    | 'anchor_rewrite'
    | 'competitor_gap'
    | 'domain_audit';
  status: 'pending' | 'running' | 'completed' | 'failed' | 'needs_input' | 'failed_partial';
  parentJob?: (number | null) | WorkflowJob;
  skillId?: string | null;
  contentBrief?: (number | null) | ContentBrief;
  pipelineKeyword?: (number | null) | Keyword;
  /**
   * Handoff: status, objective, keyFindings, evidence, openLoops, recommendedNextSkill, capApplied, scores…
   */
  handoff?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  site?: (number | null) | Site;
  /**
   * Optional target article for publish/AI jobs.
   */
  article?: (number | null) | Article;
  /**
   * Optional target page for publish/AI jobs.
   */
  page?: (number | null) | Page;
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  output?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  startedAt?: string | null;
  completedAt?: string | null;
  errorMessage?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-quotas".
 */
export interface SiteQuota {
  id: number;
  tenant?: (number | null) | Tenant;
  name: string;
  site: number | Site;
  /**
   * Cap on published pages for this site (0 = unlimited).
   */
  maxPublishedPages?: number | null;
  /**
   * Cap on automated/AI job runs per month (0 = unlimited).
   */
  maxMonthlyAiRuns?: number | null;
  /**
   * Max new posts per day (content calendar).
   */
  dailyPostCap?: number | null;
  monthlyTokenBudgetUsd?: number | null;
  monthlyImagesBudgetUsd?: number | null;
  monthlyDfsCreditBudget?: number | null;
  /**
   * Optional counters: dfs, tavily, openrouter, images
   */
  usageYtd?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "click-events".
 */
export interface ClickEvent {
  id: number;
  tenant?: (number | null) | Tenant;
  occurredAt: string;
  eventType: 'click' | 'impression';
  site?: (number | null) | Site;
  offer?: (number | null) | Offer;
  destinationUrl?: string | null;
  referrer?: string | null;
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "commissions".
 */
export interface Commission {
  id: number;
  tenant?: (number | null) | Tenant;
  amount: number;
  currency: string;
  status: 'pending' | 'approved' | 'paid' | 'rejected';
  /**
   * Commission attributed to this system user (payout / team mapping).
   */
  recipient?: (number | null) | User;
  offer?: (number | null) | Offer;
  site?: (number | null) | Site;
  periodStart?: string | null;
  periodEnd?: string | null;
  paidAt?: string | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "knowledge-base".
 */
export interface KnowledgeBase {
  id: number;
  tenant?: (number | null) | Tenant;
  title: string;
  slug?: string | null;
  /**
   * Optional scope to one site.
   */
  site?: (number | null) | Site;
  categories?: (number | Category)[] | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  status: 'draft' | 'published' | 'archived';
  notes?: string | null;
  entryType?: ('research' | 'audit' | 'monitoring' | 'decision' | 'open_loop' | 'hot_cache') | null;
  skillId?: string | null;
  subject?: string | null;
  summary?: string | null;
  payload?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  severity?: ('info' | 'warn' | 'veto') | null;
  expiresAt?: string | null;
  artifactClass?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs".
 */
export interface AuditLog {
  id: number;
  tenant?: (number | null) | Tenant;
  action: string;
  collectionSlug?: string | null;
  documentId?: string | null;
  actor?: (number | null) | User;
  occurredAt: string;
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-link-graph".
 */
export interface PageLinkGraph {
  id: number;
  tenant?: (number | null) | Tenant;
  site?: (number | null) | Site;
  fromCollection: string;
  fromId: string;
  toCollection: string;
  toId: string;
  toExternal?: string | null;
  anchorText?: string | null;
  anchorType?: ('exact' | 'partial' | 'brand' | 'generic' | 'naked_url' | 'image') | null;
  location?: ('body' | 'main_nav' | 'footer' | 'sidebar' | 'related_block' | 'breadcrumb' | 'author_bio') | null;
  contextSnippet?: string | null;
  rel?: string | null;
  createdBy?: string | null;
  lastSeenAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plugin-ai-instructions".
 */
export interface PluginAiInstruction {
  id: number;
  /**
   * Please don't change this unless you're sure of what you're doing
   */
  'schema-path'?: string | null;
  /**
   * Please don't change this unless you're sure of what you're doing
   */
  'field-type'?: ('text' | 'textarea' | 'upload' | 'richText') | null;
  'relation-to'?: string | null;
  'model-id'?: ('Oai-text' | 'dall-e' | 'gpt-image-1' | 'tts' | 'Oai-object') | null;
  /**
   * Please reload your collection after applying the changes
   */
  disabled?: boolean | null;
  /**
   * Click 'Compose' to run this custom prompt and generate content
   */
  prompt?: string | null;
  images?:
    | {
        /**
         * Please make sure the image is publicly accessible.
         */
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  system?: string | null;
  layout?: string | null;
  'Oai-text-settings'?: {
    model?:
      | ('gpt-5' | 'gpt-5-mini' | 'gpt-5-nano' | 'gpt-4.1' | 'gpt-4o' | 'gpt-4-turbo' | 'gpt-4o-mini' | 'gpt-3.5-turbo')
      | null;
    maxTokens?: number | null;
    temperature?: number | null;
    extractAttachments?: boolean | null;
  };
  'dalle-e-settings'?: {
    version?: ('dall-e-3' | 'dall-e-2') | null;
    size?: ('256x256' | '512x512' | '1024x1024' | '1792x1024' | '1024x1792') | null;
    style?: ('vivid' | 'natural') | null;
    'enable-prompt-optimization'?: boolean | null;
  };
  'gpt-image-1-settings'?: {
    version?: 'gpt-image-1' | null;
    size?: ('1024x1024' | '1024x1536' | '1536x1024' | 'auto') | null;
    quality?: ('low' | 'medium' | 'high' | 'auto') | null;
    output_format?: ('png' | 'jpeg' | 'webp') | null;
    output_compression?: number | null;
    background?: ('white' | 'transparent') | null;
    moderation?: ('auto' | 'low') | null;
  };
  'Oai-tts-settings'?: {
    voice?: ('alloy' | 'echo' | 'fable' | 'onyx' | 'nova' | 'shimmer') | null;
    model?: ('tts-1' | 'tts-1-hd') | null;
    response_format?: ('mp3' | 'opus' | 'aac' | 'flac' | 'wav' | 'pcm') | null;
    speed?: number | null;
  };
  'Oai-object-settings'?: {
    model?:
      | ('gpt-5' | 'gpt-5-mini' | 'gpt-5-nano' | 'gpt-4.1' | 'gpt-4o' | 'gpt-4-turbo' | 'gpt-4o-mini' | 'gpt-3.5-turbo')
      | null;
    maxTokens?: number | null;
    temperature?: number | null;
    extractAttachments?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Reusable trigger definitions that can be shared across workflows.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "automation-triggers".
 */
export interface AutomationTrigger {
  id: number;
  /**
   * Human-readable name for this trigger
   */
  name: string;
  /**
   * Optional description of when this trigger fires
   */
  description?: string | null;
  /**
   * The type of event that will fire this trigger
   */
  type: 'collection-hook' | 'global-hook' | 'scheduled' | 'webhook' | 'manual';
  /**
   * The target of this trigger
   */
  target?: string | null;
  /**
   * The collection to watch for events
   */
  collectionSlug?: ('articles' | 'pages') | null;
  /**
   * The specific hook event to listen for
   */
  hook?:
    | (
        | 'afterChange'
        | 'afterDelete'
        | 'afterRead'
        | 'beforeValidate'
        | 'beforeChange'
        | 'beforeDelete'
        | 'beforeRead'
        | 'afterLogin'
        | 'afterLogout'
        | 'beforeLogin'
        | 'afterForgotPassword'
        | 'afterRefresh'
        | 'afterMe'
        | 'beforeOperation'
        | 'afterOperation'
        | 'afterError'
      )
    | null;
  /**
   * The global to watch for events
   */
  globalSlug?: string | null;
  /**
   * Cron expression (e.g., "0 9 * * *" for 9 AM daily)
   */
  schedule?: string | null;
  /**
   * The URL path for this webhook (e.g., "my-webhook")
   */
  webhookPath?: string | null;
  /**
   * JSONata expression that must evaluate to true for this trigger to fire. Leave empty to always fire. Example: trigger.doc._status = "published"
   */
  condition?: string | null;
  /**
   * Human-readable explanation of the condition (for documentation)
   */
  conditionDescription?: string | null;
  /**
   * Number of workflows using this trigger
   */
  usageCount?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Reusable step templates that can be used across workflows.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "automation-steps".
 */
export interface AutomationStep {
  id: number;
  /**
   * Human-readable name for this step
   */
  name: string;
  /**
   * Optional description of what this step does
   */
  description?: string | null;
  /**
   * The type of action this step performs
   */
  type:
    | 'http-request-step'
    | 'create-document'
    | 'read-document'
    | 'update-document'
    | 'delete-document'
    | 'send-email';
  /**
   * Step configuration in JSON format. String values can use JSONata expressions for dynamic data (e.g., "trigger.doc.id")
   */
  config?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Color for the step node in the visual builder (hex code)
   */
  color?: string | null;
  /**
   * Icon name for the step (optional)
   */
  icon?: string | null;
  /**
   * Optional JSON schema for validating step inputs
   */
  inputValidation?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Retry this step if it fails
   */
  retryOnFailure?: boolean | null;
  /**
   * Maximum number of retry attempts
   */
  maxRetries?: number | null;
  /**
   * Delay between retries in milliseconds
   */
  retryDelay?: number | null;
  /**
   * Number of workflows using this step
   */
  usageCount?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Create and manage automated workflows.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "workflows".
 */
export interface Workflow {
  id: number;
  /**
   * Human-readable name for the workflow
   */
  name: string;
  /**
   * URL-safe unique identifier for this workflow
   */
  slug?: string | null;
  /**
   * Read-only workflows cannot be edited or deleted. This is typically used for seeded template workflows.
   */
  readOnly?: boolean | null;
  /**
   * Optional description of what this workflow does
   */
  description?: string | null;
  /**
   * Enable or disable this workflow
   */
  enabled?: boolean | null;
  /**
   * Triggers that can start this workflow. Uses OR logic - workflow runs if ANY trigger fires.
   */
  triggers?: (number | AutomationTrigger)[] | null;
  /**
   * Steps to execute when this workflow runs. Steps execute in order based on dependencies.
   */
  steps?:
    | {
        /**
         * Select a step from the step library
         */
        step: number | AutomationStep;
        /**
         * Unique identifier for this step within the workflow. Used for dependencies.
         */
        slug: string;
        /**
         * Override the step name for this workflow instance (optional)
         */
        stepName?: string | null;
        /**
         * Override step configuration values for this workflow. Merged with step defaults.
         */
        inputOverrides?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        /**
         * JSONata expression that must evaluate to true for this step to execute. Leave empty to always run. Example: trigger.operation = "create"
         */
        condition?: string | null;
        /**
         * Steps that must complete before this step can run. Reference steps by their slug.
         */
        dependencies?:
          | {
              /**
               * Slug of the dependent step
               */
              slug: string;
              id?: string | null;
            }[]
          | null;
        /**
         * Position in the visual workflow builder
         *
         * @minItems 2
         * @maxItems 2
         */
        position?: [number, number] | null;
        id?: string | null;
      }[]
    | null;
  /**
   * How to handle step failures
   */
  errorHandling?: ('stop' | 'continue' | 'retry') | null;
  /**
   * Maximum number of retry attempts
   */
  maxRetries?: number | null;
  /**
   * Delay between retries in milliseconds
   */
  retryDelay?: number | null;
  /**
   * Maximum execution time in milliseconds (0 for no timeout)
   */
  timeout?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "workflow-runs".
 */
export interface WorkflowRun {
  id: number;
  /**
   * Reference to the workflow that was executed
   */
  workflow: number | Workflow;
  /**
   * Version of the workflow that was executed
   */
  workflowVersion?: number | null;
  /**
   * The trigger that initiated this workflow run
   */
  firedTrigger?: (number | null) | AutomationTrigger;
  /**
   * Snapshot of the trigger context when the workflow was fired
   */
  triggerData?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Current execution status
   */
  status: 'pending' | 'running' | 'completed' | 'failed' | 'cancelled';
  /**
   * When execution began
   */
  startedAt: string;
  /**
   * When execution finished
   */
  completedAt?: string | null;
  /**
   * Total execution time in milliseconds
   */
  duration?: number | null;
  /**
   * Detailed results for each step execution
   */
  stepResults?:
    | {
        /**
         * Reference to the step that was executed
         */
        step?: (number | null) | AutomationStep;
        /**
         * Name of the step at execution time
         */
        stepName?: string | null;
        /**
         * Position of the step in the workflow
         */
        stepIndex?: number | null;
        /**
         * Step execution status
         */
        status?: ('pending' | 'running' | 'succeeded' | 'failed' | 'skipped') | null;
        /**
         * When this step started
         */
        startedAt?: string | null;
        /**
         * When this step completed
         */
        completedAt?: string | null;
        /**
         * Step execution time in milliseconds
         */
        duration?: number | null;
        /**
         * Input data passed to this step (after template resolution)
         */
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        /**
         * Output data returned by this step
         */
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        /**
         * Error message if this step failed
         */
        error?: string | null;
        /**
         * Number of retry attempts for this step
         */
        retryCount?: number | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Full execution context including trigger data and step outputs
   */
  context?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Input data provided when the workflow was triggered
   */
  inputs?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Final output data from completed steps
   */
  outputs?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * User, system, or trigger type that initiated execution
   */
  triggeredBy: string;
  /**
   * Error message if workflow execution failed
   */
  error?: string | null;
  /**
   * Detailed execution logs
   */
  logs?:
    | {
        timestamp?: string | null;
        level?: ('debug' | 'info' | 'warn' | 'error') | null;
        message?: string | null;
        /**
         * Index of the step that generated this log (optional)
         */
        stepIndex?: number | null;
        /**
         * Additional data for this log entry
         */
        data?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * API keys control which collections, resources, tools, and prompts MCP clients can access
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-mcp-api-keys".
 */
export interface PayloadMcpApiKey {
  id: number;
  /**
   * The user that the API key is associated with.
   */
  user: number | User;
  /**
   * A useful label for the API key.
   */
  label?: string | null;
  /**
   * The purpose of the API key.
   */
  description?: string | null;
  tenants?: {
    /**
     * Allow clients to find tenants.
     */
    find?: boolean | null;
    /**
     * Allow clients to create tenants.
     */
    create?: boolean | null;
    /**
     * Allow clients to update tenants.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete tenants.
     */
    delete?: boolean | null;
  };
  users?: {
    /**
     * Allow clients to find users.
     */
    find?: boolean | null;
    /**
     * Allow clients to create users.
     */
    create?: boolean | null;
    /**
     * Allow clients to update users.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete users.
     */
    delete?: boolean | null;
  };
  media?: {
    /**
     * Allow clients to find media.
     */
    find?: boolean | null;
    /**
     * Allow clients to create media.
     */
    create?: boolean | null;
    /**
     * Allow clients to update media.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete media.
     */
    delete?: boolean | null;
  };
  sites?: {
    /**
     * Allow clients to find sites.
     */
    find?: boolean | null;
    /**
     * Allow clients to create sites.
     */
    create?: boolean | null;
    /**
     * Allow clients to update sites.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete sites.
     */
    delete?: boolean | null;
  };
  affiliateNetworks?: {
    /**
     * Allow clients to find affiliate-networks.
     */
    find?: boolean | null;
    /**
     * Allow clients to create affiliate-networks.
     */
    create?: boolean | null;
    /**
     * Allow clients to update affiliate-networks.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete affiliate-networks.
     */
    delete?: boolean | null;
  };
  offers?: {
    /**
     * Allow clients to find offers.
     */
    find?: boolean | null;
    /**
     * Allow clients to create offers.
     */
    create?: boolean | null;
    /**
     * Allow clients to update offers.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete offers.
     */
    delete?: boolean | null;
  };
  categories?: {
    /**
     * Allow clients to find categories.
     */
    find?: boolean | null;
    /**
     * Allow clients to create categories.
     */
    create?: boolean | null;
    /**
     * Allow clients to update categories.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete categories.
     */
    delete?: boolean | null;
  };
  articles?: {
    /**
     * Allow clients to find articles.
     */
    find?: boolean | null;
    /**
     * Allow clients to create articles.
     */
    create?: boolean | null;
    /**
     * Allow clients to update articles.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete articles.
     */
    delete?: boolean | null;
  };
  pages?: {
    /**
     * Allow clients to find pages.
     */
    find?: boolean | null;
    /**
     * Allow clients to create pages.
     */
    create?: boolean | null;
    /**
     * Allow clients to update pages.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete pages.
     */
    delete?: boolean | null;
  };
  keywords?: {
    /**
     * Allow clients to find keywords.
     */
    find?: boolean | null;
    /**
     * Allow clients to create keywords.
     */
    create?: boolean | null;
    /**
     * Allow clients to update keywords.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete keywords.
     */
    delete?: boolean | null;
  };
  workflowJobs?: {
    /**
     * Allow clients to find workflow-jobs.
     */
    find?: boolean | null;
    /**
     * Allow clients to create workflow-jobs.
     */
    create?: boolean | null;
    /**
     * Allow clients to update workflow-jobs.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete workflow-jobs.
     */
    delete?: boolean | null;
  };
  knowledgeBase?: {
    /**
     * Allow clients to find knowledge-base.
     */
    find?: boolean | null;
    /**
     * Allow clients to create knowledge-base.
     */
    create?: boolean | null;
    /**
     * Allow clients to update knowledge-base.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete knowledge-base.
     */
    delete?: boolean | null;
  };
  rankings?: {
    /**
     * Allow clients to find rankings.
     */
    find?: boolean | null;
    /**
     * Allow clients to create rankings.
     */
    create?: boolean | null;
    /**
     * Allow clients to update rankings.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete rankings.
     */
    delete?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  collection: 'payload-mcp-api-keys';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug:
          | 'inline'
          | 'http-request-step'
          | 'create-document'
          | 'read-document'
          | 'update-document'
          | 'delete-document'
          | 'send-email';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?:
    | (
        | 'inline'
        | 'http-request-step'
        | 'create-document'
        | 'read-document'
        | 'update-document'
        | 'delete-document'
        | 'send-email'
      )
    | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  /**
   * Workflow that created this job
   */
  automationWorkflow?: (number | null) | Workflow;
  /**
   * Workflow run that created this job
   */
  automationWorkflowRun?: (number | null) | WorkflowRun;
  /**
   * Trigger that initiated the workflow
   */
  automationTrigger?: (number | null) | AutomationTrigger;
  /**
   * Name of the workflow step that created this job
   */
  automationStepName?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'announcements';
        value: number | Announcement;
      } | null)
    | ({
        relationTo: 'sites';
        value: number | Site;
      } | null)
    | ({
        relationTo: 'site-blueprints';
        value: number | SiteBlueprint;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'social-platforms';
        value: number | SocialPlatform;
      } | null)
    | ({
        relationTo: 'social-accounts';
        value: number | SocialAccount;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'keywords';
        value: number | Keyword;
      } | null)
    | ({
        relationTo: 'content-briefs';
        value: number | ContentBrief;
      } | null)
    | ({
        relationTo: 'serp-snapshots';
        value: number | SerpSnapshot;
      } | null)
    | ({
        relationTo: 'authors';
        value: number | Author;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'rankings';
        value: number | Ranking;
      } | null)
    | ({
        relationTo: 'workflow-jobs';
        value: number | WorkflowJob;
      } | null)
    | ({
        relationTo: 'site-quotas';
        value: number | SiteQuota;
      } | null)
    | ({
        relationTo: 'affiliate-networks';
        value: number | AffiliateNetwork;
      } | null)
    | ({
        relationTo: 'offers';
        value: number | Offer;
      } | null)
    | ({
        relationTo: 'click-events';
        value: number | ClickEvent;
      } | null)
    | ({
        relationTo: 'commissions';
        value: number | Commission;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'knowledge-base';
        value: number | KnowledgeBase;
      } | null)
    | ({
        relationTo: 'audit-logs';
        value: number | AuditLog;
      } | null)
    | ({
        relationTo: 'tenants';
        value: number | Tenant;
      } | null)
    | ({
        relationTo: 'original-evidence';
        value: number | OriginalEvidence;
      } | null)
    | ({
        relationTo: 'landing-templates';
        value: number | LandingTemplate;
      } | null)
    | ({
        relationTo: 'page-link-graph';
        value: number | PageLinkGraph;
      } | null)
    | ({
        relationTo: 'plugin-ai-instructions';
        value: number | PluginAiInstruction;
      } | null)
    | ({
        relationTo: 'automation-triggers';
        value: number | AutomationTrigger;
      } | null)
    | ({
        relationTo: 'automation-steps';
        value: number | AutomationStep;
      } | null)
    | ({
        relationTo: 'workflows';
        value: number | Workflow;
      } | null)
    | ({
        relationTo: 'workflow-runs';
        value: number | WorkflowRun;
      } | null)
    | ({
        relationTo: 'payload-mcp-api-keys';
        value: number | PayloadMcpApiKey;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'payload-mcp-api-keys';
        value: number | PayloadMcpApiKey;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'payload-mcp-api-keys';
        value: number | PayloadMcpApiKey;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "announcements_select".
 */
export interface AnnouncementsSelect<T extends boolean = true> {
  tenant?: T;
  kind?: T;
  teamLead?: T;
  author?: T;
  title?: T;
  body?: T;
  isActive?: T;
  isPinned?: T;
  startsAt?: T;
  endsAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sites_select".
 */
export interface SitesSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  slug?: T;
  primaryDomain?: T;
  status?: T;
  blueprint?: T;
  landingTemplate?: T;
  operators?: T;
  notes?: T;
  landingBrowserTitle?: T;
  landingSiteName?: T;
  landingTagline?: T;
  landingLoggedInTitle?: T;
  landingLoggedInSubtitle?: T;
  landingFooterLine?: T;
  landingCtaLabel?: T;
  landingBgColor?: T;
  landingTextColor?: T;
  landingMutedColor?: T;
  landingCtaBgColor?: T;
  landingCtaTextColor?: T;
  landingFontPreset?: T;
  landingBlogPrimaryColor?: T;
  landingBlogAccentColor?: T;
  landingBlogContentBgColor?: T;
  landingBlogCardBgColor?: T;
  landingBlogHeaderTextColor?: T;
  landingBlogHeadingColor?: T;
  landingBlogBodyColor?: T;
  landingAboutTitle?: T;
  landingAboutBio?: T;
  landingAboutImage?: T;
  landingAboutCtaLabel?: T;
  landingAboutCtaHref?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-blueprints_select".
 */
export interface SiteBlueprintsSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  slug?: T;
  site?: T;
  description?: T;
  templateConfig?: T;
  designBrowserTitle?: T;
  designSiteName?: T;
  designTagline?: T;
  designLoggedInTitle?: T;
  designLoggedInSubtitle?: T;
  designFooterLine?: T;
  designCtaLabel?: T;
  designBgColor?: T;
  designTextColor?: T;
  designMutedColor?: T;
  designCtaBgColor?: T;
  designCtaTextColor?: T;
  designFontPreset?: T;
  designBlogPrimaryColor?: T;
  designBlogAccentColor?: T;
  designBlogContentBgColor?: T;
  designBlogCardBgColor?: T;
  designBlogHeaderTextColor?: T;
  designBlogHeadingColor?: T;
  designBlogBodyColor?: T;
  designAboutTitle?: T;
  designAboutBio?: T;
  designAboutImage?: T;
  designAboutCtaLabel?: T;
  designAboutCtaHref?: T;
  trustAssetsTemplate?: T;
  mainNavTemplate?: T;
  footerTemplate?: T;
  showBreadcrumb?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  slug?: T;
  site?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  slug?: T;
  locale?: T;
  site?: T;
  categories?: T;
  featuredImage?: T;
  body?: T;
  status?: T;
  publishedAt?: T;
  excerpt?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  tenant?: T;
  site?: T;
  fromPath?: T;
  toPath?: T;
  statusCode?: T;
  enabled?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "social-platforms_select".
 */
export interface SocialPlatformsSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  slug?: T;
  status?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "social-accounts_select".
 */
export interface SocialAccountsSelect<T extends boolean = true> {
  tenant?: T;
  platform?: T;
  site?: T;
  handle?: T;
  status?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  tenant?: T;
  alt?: T;
  site?: T;
  assetClass?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "keywords_select".
 */
export interface KeywordsSelect<T extends boolean = true> {
  tenant?: T;
  term?: T;
  slug?: T;
  site?: T;
  status?: T;
  notes?: T;
  volume?: T;
  keywordDifficulty?: T;
  cpc?: T;
  trend?: T;
  intent?: T;
  geoFriendly?: T;
  pillar?: T;
  serpFeatures?: T;
  lastRefreshedAt?: T;
  opportunityScore?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "content-briefs_select".
 */
export interface ContentBriefsSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  primaryKeyword?: T;
  site?: T;
  intentSummary?: T;
  outline?: T;
  sources?: T;
  targetWordCount?: T;
  competitors?: T;
  peopleAlsoAsk?: T;
  schemaHints?: T;
  status?: T;
  skillId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "serp-snapshots_select".
 */
export interface SerpSnapshotsSelect<T extends boolean = true> {
  tenant?: T;
  searchQuery?: T;
  keyword?: T;
  site?: T;
  engine?: T;
  location?: T;
  device?: T;
  capturedAt?: T;
  raw?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors_select".
 */
export interface AuthorsSelect<T extends boolean = true> {
  tenant?: T;
  displayName?: T;
  slug?: T;
  role?: T;
  headshot?: T;
  bioLexical?: T;
  credentials?: T;
  expertiseAreas?: T;
  sameAs?: T;
  schemaPersonJsonLd?: T;
  gdprLawfulBasis?: T;
  gdprRegion?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  slug?: T;
  locale?: T;
  site?: T;
  categories?: T;
  featuredImage?: T;
  body?: T;
  status?: T;
  publishedAt?: T;
  excerpt?: T;
  primaryKeyword?: T;
  secondaryKeywords?: T;
  contentTemplate?: T;
  qualityScore?: T;
  eeatCheck?: T;
  schemaJsonLd?: T;
  vetoCodes?: T;
  featuredOffers?: T;
  author?: T;
  reviewedBy?: T;
  originalEvidence?: T;
  sourceBrief?: T;
  mergedInto?: T;
  sectionSummaries?: T;
  metaVariants?: T;
  lifecycleStage?: T;
  probationEndsAt?: T;
  bestPosition?: T;
  currentPosition?: T;
  impressions30d?: T;
  clicks30d?: T;
  nextActionAt?: T;
  optimizationHistory?: T;
  linkBudgetWarnings?: T;
  skipLinkBudgetCheck?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rankings_select".
 */
export interface RankingsSelect<T extends boolean = true> {
  tenant?: T;
  keyword?: T;
  site?: T;
  searchQuery?: T;
  serpPosition?: T;
  serpUrl?: T;
  capturedAt?: T;
  notes?: T;
  rawSerp?: T;
  change?: T;
  isAiOverviewHit?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "workflow-jobs_select".
 */
export interface WorkflowJobsSelect<T extends boolean = true> {
  tenant?: T;
  label?: T;
  jobType?: T;
  status?: T;
  parentJob?: T;
  skillId?: T;
  contentBrief?: T;
  pipelineKeyword?: T;
  handoff?: T;
  site?: T;
  article?: T;
  page?: T;
  input?: T;
  output?: T;
  startedAt?: T;
  completedAt?: T;
  errorMessage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-quotas_select".
 */
export interface SiteQuotasSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  site?: T;
  maxPublishedPages?: T;
  maxMonthlyAiRuns?: T;
  dailyPostCap?: T;
  monthlyTokenBudgetUsd?: T;
  monthlyImagesBudgetUsd?: T;
  monthlyDfsCreditBudget?: T;
  usageYtd?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "affiliate-networks_select".
 */
export interface AffiliateNetworksSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  slug?: T;
  websiteUrl?: T;
  status?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "offers_select".
 */
export interface OffersSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  slug?: T;
  network?: T;
  sites?: T;
  status?: T;
  externalId?: T;
  targetUrl?: T;
  commissionNotes?: T;
  amazon?:
    | T
    | {
        asin?: T;
        priceCents?: T;
        currency?: T;
        ratingAvg?: T;
        reviewCount?: T;
        imageUrl?: T;
        primeEligible?: T;
        merchantLastSyncedAt?: T;
        merchantRaw?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "click-events_select".
 */
export interface ClickEventsSelect<T extends boolean = true> {
  tenant?: T;
  occurredAt?: T;
  eventType?: T;
  site?: T;
  offer?: T;
  destinationUrl?: T;
  referrer?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "commissions_select".
 */
export interface CommissionsSelect<T extends boolean = true> {
  tenant?: T;
  amount?: T;
  currency?: T;
  status?: T;
  recipient?: T;
  offer?: T;
  site?: T;
  periodStart?: T;
  periodEnd?: T;
  paidAt?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  teamLead?: T;
  roles?: T;
  tenants?:
    | T
    | {
        tenant?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "knowledge-base_select".
 */
export interface KnowledgeBaseSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  slug?: T;
  site?: T;
  categories?: T;
  body?: T;
  status?: T;
  notes?: T;
  entryType?: T;
  skillId?: T;
  subject?: T;
  summary?: T;
  payload?: T;
  severity?: T;
  expiresAt?: T;
  artifactClass?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs_select".
 */
export interface AuditLogsSelect<T extends boolean = true> {
  tenant?: T;
  action?: T;
  collectionSlug?: T;
  documentId?: T;
  actor?: T;
  occurredAt?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants_select".
 */
export interface TenantsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  domain?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "original-evidence_select".
 */
export interface OriginalEvidenceSelect<T extends boolean = true> {
  tenant?: T;
  kind?: T;
  product?: T;
  article?: T;
  capturedAt?: T;
  capturedBy?: T;
  media?: T;
  watermarkApplied?: T;
  exifPreserved?: T;
  notes?: T;
  verifiedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "landing-templates_select".
 */
export interface LandingTemplatesSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  slug?: T;
  description?: T;
  previewUrl?: T;
  landingBrowserTitle?: T;
  landingSiteName?: T;
  landingTagline?: T;
  landingLoggedInTitle?: T;
  landingLoggedInSubtitle?: T;
  landingFooterLine?: T;
  landingCtaLabel?: T;
  landingBgColor?: T;
  landingTextColor?: T;
  landingMutedColor?: T;
  landingCtaBgColor?: T;
  landingCtaTextColor?: T;
  landingFontPreset?: T;
  blogPrimaryColor?: T;
  blogAccentColor?: T;
  blogContentBgColor?: T;
  blogCardBgColor?: T;
  blogHeaderTextColor?: T;
  blogHeadingColor?: T;
  blogBodyColor?: T;
  aboutTitle?: T;
  aboutBio?: T;
  aboutImage?: T;
  aboutCtaLabel?: T;
  aboutCtaHref?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-link-graph_select".
 */
export interface PageLinkGraphSelect<T extends boolean = true> {
  tenant?: T;
  site?: T;
  fromCollection?: T;
  fromId?: T;
  toCollection?: T;
  toId?: T;
  toExternal?: T;
  anchorText?: T;
  anchorType?: T;
  location?: T;
  contextSnippet?: T;
  rel?: T;
  createdBy?: T;
  lastSeenAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plugin-ai-instructions_select".
 */
export interface PluginAiInstructionsSelect<T extends boolean = true> {
  'schema-path'?: T;
  'field-type'?: T;
  'relation-to'?: T;
  'model-id'?: T;
  disabled?: T;
  prompt?: T;
  images?:
    | T
    | {
        image?: T;
        id?: T;
      };
  system?: T;
  layout?: T;
  'Oai-text-settings'?:
    | T
    | {
        model?: T;
        maxTokens?: T;
        temperature?: T;
        extractAttachments?: T;
      };
  'dalle-e-settings'?:
    | T
    | {
        version?: T;
        size?: T;
        style?: T;
        'enable-prompt-optimization'?: T;
      };
  'gpt-image-1-settings'?:
    | T
    | {
        version?: T;
        size?: T;
        quality?: T;
        output_format?: T;
        output_compression?: T;
        background?: T;
        moderation?: T;
      };
  'Oai-tts-settings'?:
    | T
    | {
        voice?: T;
        model?: T;
        response_format?: T;
        speed?: T;
      };
  'Oai-object-settings'?:
    | T
    | {
        model?: T;
        maxTokens?: T;
        temperature?: T;
        extractAttachments?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "automation-triggers_select".
 */
export interface AutomationTriggersSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  type?: T;
  target?: T;
  collectionSlug?: T;
  hook?: T;
  globalSlug?: T;
  schedule?: T;
  webhookPath?: T;
  condition?: T;
  conditionDescription?: T;
  usageCount?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "automation-steps_select".
 */
export interface AutomationStepsSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  type?: T;
  config?: T;
  color?: T;
  icon?: T;
  inputValidation?: T;
  retryOnFailure?: T;
  maxRetries?: T;
  retryDelay?: T;
  usageCount?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "workflows_select".
 */
export interface WorkflowsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  readOnly?: T;
  description?: T;
  enabled?: T;
  triggers?: T;
  steps?:
    | T
    | {
        step?: T;
        slug?: T;
        stepName?: T;
        inputOverrides?: T;
        condition?: T;
        dependencies?:
          | T
          | {
              slug?: T;
              id?: T;
            };
        position?: T;
        id?: T;
      };
  errorHandling?: T;
  maxRetries?: T;
  retryDelay?: T;
  timeout?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "workflow-runs_select".
 */
export interface WorkflowRunsSelect<T extends boolean = true> {
  workflow?: T;
  workflowVersion?: T;
  firedTrigger?: T;
  triggerData?: T;
  status?: T;
  startedAt?: T;
  completedAt?: T;
  duration?: T;
  stepResults?:
    | T
    | {
        step?: T;
        stepName?: T;
        stepIndex?: T;
        status?: T;
        startedAt?: T;
        completedAt?: T;
        duration?: T;
        input?: T;
        output?: T;
        error?: T;
        retryCount?: T;
        id?: T;
      };
  context?: T;
  inputs?: T;
  outputs?: T;
  triggeredBy?: T;
  error?: T;
  logs?:
    | T
    | {
        timestamp?: T;
        level?: T;
        message?: T;
        stepIndex?: T;
        data?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-mcp-api-keys_select".
 */
export interface PayloadMcpApiKeysSelect<T extends boolean = true> {
  user?: T;
  label?: T;
  description?: T;
  tenants?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  users?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  media?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  sites?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  affiliateNetworks?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  offers?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  categories?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  articles?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  pages?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  keywords?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  workflowJobs?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  knowledgeBase?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  rankings?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  automationWorkflow?: T;
  automationWorkflowRun?: T;
  automationTrigger?: T;
  automationStepName?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "commission-rules".
 */
export interface CommissionRule {
  id: number;
  /**
   * JSON for default splits, floors, approval policy, etc.
   */
  rules?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  notes?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * 未匹配到具体站点域名时使用；各站点可在「站点」里覆盖。
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "public-landing".
 */
export interface PublicLanding {
  id: number;
  siteName: string;
  /**
   * 留空则与网站名称相同。
   */
  browserTitle?: string | null;
  tagline?: string | null;
  loggedInTitle?: string | null;
  loggedInSubtitle?: string | null;
  footerLine?: string | null;
  adminCtaLabel?: string | null;
  backgroundColor?: string | null;
  textColor?: string | null;
  mutedTextColor?: string | null;
  ctaBackgroundColor?: string | null;
  ctaTextColor?: string | null;
  fontPreset?: ('system' | 'serif' | 'noto_sans_sc') | null;
  blogPrimaryColor?: string | null;
  blogAccentColor?: string | null;
  blogContentBgColor?: string | null;
  blogCardBgColor?: string | null;
  blogHeaderTextColor?: string | null;
  blogHeadingColor?: string | null;
  blogBodyColor?: string | null;
  aboutTitle?: string | null;
  aboutBio?: string | null;
  aboutImage?: (number | null) | Media;
  aboutCtaLabel?: string | null;
  aboutCtaHref?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quota-rules".
 */
export interface QuotaRule {
  id: number;
  /**
   * JSON for default per-site caps and tenant-wide limits.
   */
  rules?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  notes?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admin-branding".
 */
export interface AdminBranding {
  id: number;
  /**
   * Shown in the admin browser tab as “… | {name}” instead of “… - Payload”. If empty, use env `NEXT_PUBLIC_ADMIN_BRAND_NAME` as fallback; if that is also unset, only the Payload suffix is removed (page name only).
   */
  brandName?: string | null;
  logo?: (number | null) | Media;
  /**
   * e.g. #0f172a
   */
  primaryColor?: string | null;
  supportEmail?: string | null;
  notes?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "llm-prompts".
 */
export interface LlmPrompt {
  id: number;
  /**
   * Provider model id (e.g. gpt-4o-mini).
   */
  defaultModel?: string | null;
  temperature?: number | null;
  globalSystemPrompt?: string | null;
  apiNotes?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "prompt-library".
 */
export interface PromptLibrary {
  id: number;
  entries?:
    | {
        name: string;
        body: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Map skillId -> partial system prompt override (used by skillPrompts.get)
   */
  skillOverrides?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pipeline-settings".
 */
export interface PipelineSetting {
  id: number;
  tavilyEnabled?: boolean | null;
  dataForSeoEnabled?: boolean | null;
  togetherImageEnabled?: boolean | null;
  /**
   * OpenRouter model id
   */
  defaultLlmModel?: string | null;
  defaultImageModel?: string | null;
  amazonMarketplace?: string | null;
  defaultLocale?: string | null;
  defaultRegion?: string | null;
  frugalMode?: boolean | null;
  /**
   * Per contentType 8-dimension weights (C,O,R,E,Exp,Ept,A,T) sum=100
   */
  eeatWeights?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  llmModelsBySection?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  sectionParallelism?: number | null;
  sectionParallelWhitelist?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  sectionMaxRetry?: number | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "commission-rules_select".
 */
export interface CommissionRulesSelect<T extends boolean = true> {
  rules?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "public-landing_select".
 */
export interface PublicLandingSelect<T extends boolean = true> {
  siteName?: T;
  browserTitle?: T;
  tagline?: T;
  loggedInTitle?: T;
  loggedInSubtitle?: T;
  footerLine?: T;
  adminCtaLabel?: T;
  backgroundColor?: T;
  textColor?: T;
  mutedTextColor?: T;
  ctaBackgroundColor?: T;
  ctaTextColor?: T;
  fontPreset?: T;
  blogPrimaryColor?: T;
  blogAccentColor?: T;
  blogContentBgColor?: T;
  blogCardBgColor?: T;
  blogHeaderTextColor?: T;
  blogHeadingColor?: T;
  blogBodyColor?: T;
  aboutTitle?: T;
  aboutBio?: T;
  aboutImage?: T;
  aboutCtaLabel?: T;
  aboutCtaHref?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quota-rules_select".
 */
export interface QuotaRulesSelect<T extends boolean = true> {
  rules?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admin-branding_select".
 */
export interface AdminBrandingSelect<T extends boolean = true> {
  brandName?: T;
  logo?: T;
  primaryColor?: T;
  supportEmail?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "llm-prompts_select".
 */
export interface LlmPromptsSelect<T extends boolean = true> {
  defaultModel?: T;
  temperature?: T;
  globalSystemPrompt?: T;
  apiNotes?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "prompt-library_select".
 */
export interface PromptLibrarySelect<T extends boolean = true> {
  entries?:
    | T
    | {
        name?: T;
        body?: T;
        id?: T;
      };
  skillOverrides?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pipeline-settings_select".
 */
export interface PipelineSettingsSelect<T extends boolean = true> {
  tavilyEnabled?: T;
  dataForSeoEnabled?: T;
  togetherImageEnabled?: T;
  defaultLlmModel?: T;
  defaultImageModel?: T;
  amazonMarketplace?: T;
  defaultLocale?: T;
  defaultRegion?: T;
  frugalMode?: T;
  eeatWeights?: T;
  llmModelsBySection?: T;
  sectionParallelism?: T;
  sectionParallelWhitelist?: T;
  sectionMaxRetry?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskHttp-request-step".
 */
export interface TaskHttpRequestStep {
  input: {
    /**
     * The URL to make the HTTP request to
     */
    url: string;
    /**
     * HTTP method to use
     */
    method?: ('GET' | 'POST' | 'PUT' | 'DELETE' | 'PATCH') | null;
    /**
     * HTTP headers as JSON object (e.g., {"Content-Type": "application/json"})
     */
    headers?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    /**
     * Request body data. Use JSONPath to reference values (e.g., {"postId": "$.trigger.doc.id", "title": "$.trigger.doc.title"})
     */
    body?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    /**
     * Request timeout in milliseconds (default: 30000)
     */
    timeout?: number | null;
    authentication?: {
      /**
       * Authentication method
       */
      type?: ('none' | 'bearer' | 'basic' | 'apikey') | null;
      /**
       * Bearer token value
       */
      token?: string | null;
      /**
       * Basic auth username
       */
      username?: string | null;
      /**
       * Basic auth password
       */
      password?: string | null;
      /**
       * API key header name (e.g., "X-API-Key")
       */
      headerName?: string | null;
      /**
       * API key value
       */
      headerValue?: string | null;
    };
    /**
     * Number of retry attempts on failure (max: 5)
     */
    retries?: number | null;
    /**
     * Delay between retries in milliseconds
     */
    retryDelay?: number | null;
  };
  output: {
    /**
     * HTTP status code
     */
    status?: number | null;
    /**
     * HTTP status text
     */
    statusText?: string | null;
    /**
     * Response headers
     */
    headers?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    /**
     * Response body
     */
    body?: string | null;
    /**
     * Parsed response data (if JSON)
     */
    data?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    /**
     * Request duration in milliseconds
     */
    duration?: number | null;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskCreate-document".
 */
export interface TaskCreateDocument {
  input: {
    /**
     * The collection slug to create a document in
     */
    collectionSlug: string;
    /**
     * The document data to create. Use JSONPath to reference trigger data (e.g., {"title": "$.trigger.doc.title", "author": "$.trigger.doc.author"})
     */
    data:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    /**
     * Create as draft (if collection has drafts enabled)
     */
    draft?: boolean | null;
    /**
     * Locale for the document (if localization is enabled)
     */
    locale?: string | null;
  };
  output: {
    /**
     * The created document
     */
    doc?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    /**
     * The ID of the created document
     */
    id?: string | null;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskRead-document".
 */
export interface TaskReadDocument {
  input: {
    /**
     * The collection slug to read from
     */
    collectionSlug: string;
    /**
     * The ID of a specific document to read. Use JSONPath (e.g., "$.trigger.doc.relatedId"). Leave empty to find multiple.
     */
    id?: string | null;
    /**
     * Query conditions to find documents when ID is not provided. Use JSONPath in values (e.g., {"category": "$.trigger.doc.category", "status": "published"})
     */
    where?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    /**
     * Maximum number of documents to return (default: 10)
     */
    limit?: number | null;
    /**
     * Field to sort by (prefix with - for descending order)
     */
    sort?: string | null;
    /**
     * Locale for the document (if localization is enabled)
     */
    locale?: string | null;
    /**
     * Depth of relationships to populate (0-10)
     */
    depth?: number | null;
  };
  output: {
    /**
     * The document(s) found
     */
    doc?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    /**
     * Total number of documents matching the query
     */
    totalDocs?: number | null;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskUpdate-document".
 */
export interface TaskUpdateDocument {
  input: {
    /**
     * The collection slug to update a document in
     */
    collectionSlug: string;
    /**
     * The ID of the document to update. Use JSONPath to reference IDs (e.g., "$.trigger.doc.id" or "$.steps.previousStep.output.id")
     */
    id: string;
    /**
     * The data to update the document with. Use JSONPath to reference values (e.g., {"status": "$.trigger.doc.status", "updatedBy": "$.trigger.user.id"})
     */
    data:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    /**
     * Update as draft (if collection has drafts enabled)
     */
    draft?: boolean | null;
    /**
     * Locale for the document (if localization is enabled)
     */
    locale?: string | null;
  };
  output: {
    /**
     * The updated document
     */
    doc?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    /**
     * The ID of the updated document
     */
    id?: string | null;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskDelete-document".
 */
export interface TaskDeleteDocument {
  input: {
    /**
     * The collection slug to delete from
     */
    collectionSlug: string;
    /**
     * The ID of a specific document to delete. Use JSONPath (e.g., "$.trigger.doc.id"). Leave empty to delete multiple.
     */
    id?: string | null;
    /**
     * Query conditions to find documents to delete when ID is not provided. Use JSONPath in values (e.g., {"author": "$.trigger.doc.author"})
     */
    where?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  output: {
    /**
     * The deleted document(s)
     */
    doc?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    /**
     * Number of documents deleted
     */
    deletedCount?: number | null;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSend-email".
 */
export interface TaskSendEmail {
  input: {
    /**
     * Recipient email address. Use JSONPath for dynamic values (e.g., "$.trigger.doc.email" or "$.trigger.user.email")
     */
    to: string;
    /**
     * Sender email address. Use JSONPath if needed (e.g., "$.trigger.doc.senderEmail"). Uses default if not provided.
     */
    from?: string | null;
    /**
     * Email subject line. Can include JSONPath references (e.g., "Order #$.trigger.doc.orderNumber received")
     */
    subject: string;
    /**
     * Plain text email content. Use JSONPath to include dynamic content (e.g., "Dear $.trigger.doc.customerName, your order #$.trigger.doc.id has been received.")
     */
    text?: string | null;
    /**
     * HTML email content. Use JSONPath for dynamic values (e.g., "<h1>Order #$.trigger.doc.orderNumber</h1>")
     */
    html?: string | null;
    /**
     * CC recipients
     */
    cc?: string[] | null;
    /**
     * BCC recipients
     */
    bcc?: string[] | null;
  };
  output: {
    /**
     * Email message ID from the mail server
     */
    messageId?: string | null;
    /**
     * Response from the mail server
     */
    response?: string | null;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}