/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    'payload-mcp-api-keys': PayloadMcpApiKeyAuthOperations;
  };
  blocks: {};
  collections: {
    announcements: Announcement;
    sites: Site;
    'site-blueprints': SiteBlueprint;
    categories: Category;
    articles: Article;
    pages: Page;
    'social-platforms': SocialPlatform;
    'social-accounts': SocialAccount;
    media: Media;
    keywords: Keyword;
    rankings: Ranking;
    'workflow-jobs': WorkflowJob;
    'site-quotas': SiteQuota;
    'affiliate-networks': AffiliateNetwork;
    offers: Offer;
    'click-events': ClickEvent;
    commissions: Commission;
    users: User;
    'knowledge-base': KnowledgeBase;
    'audit-logs': AuditLog;
    tenants: Tenant;
    'payload-mcp-api-keys': PayloadMcpApiKey;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    announcements: AnnouncementsSelect<false> | AnnouncementsSelect<true>;
    sites: SitesSelect<false> | SitesSelect<true>;
    'site-blueprints': SiteBlueprintsSelect<false> | SiteBlueprintsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'social-platforms': SocialPlatformsSelect<false> | SocialPlatformsSelect<true>;
    'social-accounts': SocialAccountsSelect<false> | SocialAccountsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    keywords: KeywordsSelect<false> | KeywordsSelect<true>;
    rankings: RankingsSelect<false> | RankingsSelect<true>;
    'workflow-jobs': WorkflowJobsSelect<false> | WorkflowJobsSelect<true>;
    'site-quotas': SiteQuotasSelect<false> | SiteQuotasSelect<true>;
    'affiliate-networks': AffiliateNetworksSelect<false> | AffiliateNetworksSelect<true>;
    offers: OffersSelect<false> | OffersSelect<true>;
    'click-events': ClickEventsSelect<false> | ClickEventsSelect<true>;
    commissions: CommissionsSelect<false> | CommissionsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'knowledge-base': KnowledgeBaseSelect<false> | KnowledgeBaseSelect<true>;
    'audit-logs': AuditLogsSelect<false> | AuditLogsSelect<true>;
    tenants: TenantsSelect<false> | TenantsSelect<true>;
    'payload-mcp-api-keys': PayloadMcpApiKeysSelect<false> | PayloadMcpApiKeysSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'commission-rules': CommissionRule;
    'quota-rules': QuotaRule;
    'admin-branding': AdminBranding;
    'llm-prompts': LlmPrompt;
    'prompt-library': PromptLibrary;
  };
  globalsSelect: {
    'commission-rules': CommissionRulesSelect<false> | CommissionRulesSelect<true>;
    'quota-rules': QuotaRulesSelect<false> | QuotaRulesSelect<true>;
    'admin-branding': AdminBrandingSelect<false> | AdminBrandingSelect<true>;
    'llm-prompts': LlmPromptsSelect<false> | LlmPromptsSelect<true>;
    'prompt-library': PromptLibrarySelect<false> | PromptLibrarySelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User | PayloadMcpApiKey;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface PayloadMcpApiKeyAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * 系统公告（租户内广播）与团队公告（组长发布给本组）。
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "announcements".
 */
export interface Announcement {
  id: number;
  tenant?: (number | null) | Tenant;
  /**
   * 组长仅可创建「团队公告」。系统公告仅超级管理员可发布。
   */
  kind: 'system' | 'team';
  /**
   * 团队公告面向该组长及其组员（users.teamLead 指向此用户）。
   */
  teamLead?: (number | null) | User;
  /**
   * 创建者（自动填充）。
   */
  author?: (number | null) | User;
  title: string;
  body: string;
  isActive?: boolean | null;
  /**
   * 置顶显示（前端可按需排序）。
   */
  isPinned?: boolean | null;
  startsAt?: string | null;
  endsAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants".
 */
export interface Tenant {
  id: number;
  name: string;
  slug: string;
  domain: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Optional team lead for commission / reporting (same tenant; refine access in PRD as needed).
   */
  teamLead?: (number | null) | User;
  /**
   * Super Admin can access every tenant and all tenant-scoped content. Only Super Admins can grant this role.
   */
  roles: ('user' | 'super-admin')[];
  tenants?:
    | {
        tenant: number | Tenant;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sites".
 */
export interface Site {
  id: number;
  tenant?: (number | null) | Tenant;
  name: string;
  /**
   * URL-safe key; pair with tenant for uniqueness in your workflows.
   */
  slug: string;
  primaryDomain: string;
  status: 'draft' | 'active' | 'archived';
  /**
   * Optional layout/template blueprint for this site.
   */
  blueprint?: (number | null) | SiteBlueprint;
  /**
   * Users who operate this site (optional; tenant scoping still applies).
   */
  operators?: (number | User)[] | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-blueprints".
 */
export interface SiteBlueprint {
  id: number;
  tenant?: (number | null) | Tenant;
  name: string;
  slug: string;
  description?: string | null;
  /**
   * Arbitrary JSON for themes, sections, or generator defaults.
   */
  templateConfig?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  tenant?: (number | null) | Tenant;
  name: string;
  slug: string;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  tenant?: (number | null) | Tenant;
  title: string;
  slug?: string | null;
  /**
   * Owning site (optional while migrating legacy content).
   */
  site?: (number | null) | Site;
  categories?: (number | Category)[] | null;
  featuredImage?: (number | null) | Media;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  status: 'draft' | 'published' | 'archived';
  publishedAt?: string | null;
  excerpt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  tenant?: (number | null) | Tenant;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  tenant?: (number | null) | Tenant;
  title: string;
  slug?: string | null;
  /**
   * Owning site (optional while migrating legacy content).
   */
  site?: (number | null) | Site;
  categories?: (number | Category)[] | null;
  featuredImage?: (number | null) | Media;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  status: 'draft' | 'published' | 'archived';
  publishedAt?: string | null;
  excerpt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "social-platforms".
 */
export interface SocialPlatform {
  id: number;
  tenant?: (number | null) | Tenant;
  name: string;
  slug: string;
  status: 'active' | 'paused';
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "social-accounts".
 */
export interface SocialAccount {
  id: number;
  tenant?: (number | null) | Tenant;
  platform: number | SocialPlatform;
  site?: (number | null) | Site;
  handle: string;
  status: 'active' | 'disconnected';
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "keywords".
 */
export interface Keyword {
  id: number;
  tenant?: (number | null) | Tenant;
  term: string;
  slug?: string | null;
  /**
   * Optional: scope this keyword to one site.
   */
  site?: (number | null) | Site;
  status: 'draft' | 'active' | 'archived';
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rankings".
 */
export interface Ranking {
  id: number;
  tenant?: (number | null) | Tenant;
  keyword?: (number | null) | Keyword;
  site?: (number | null) | Site;
  searchQuery: string;
  serpPosition?: number | null;
  serpUrl?: string | null;
  capturedAt: string;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "workflow-jobs".
 */
export interface WorkflowJob {
  id: number;
  tenant?: (number | null) | Tenant;
  label: string;
  jobType: 'publish' | 'sync' | 'ai_generate' | 'custom';
  status: 'pending' | 'running' | 'completed' | 'failed';
  site?: (number | null) | Site;
  /**
   * Optional target article for publish/AI jobs.
   */
  article?: (number | null) | Article;
  /**
   * Optional target page for publish/AI jobs.
   */
  page?: (number | null) | Page;
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  output?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  startedAt?: string | null;
  completedAt?: string | null;
  errorMessage?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-quotas".
 */
export interface SiteQuota {
  id: number;
  tenant?: (number | null) | Tenant;
  name: string;
  site: number | Site;
  /**
   * Cap on published pages for this site (0 = unlimited).
   */
  maxPublishedPages?: number | null;
  /**
   * Cap on automated/AI job runs per month (0 = unlimited).
   */
  maxMonthlyAiRuns?: number | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "affiliate-networks".
 */
export interface AffiliateNetwork {
  id: number;
  tenant?: (number | null) | Tenant;
  name: string;
  slug: string;
  websiteUrl?: string | null;
  status: 'active' | 'paused';
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "offers".
 */
export interface Offer {
  id: number;
  tenant?: (number | null) | Tenant;
  title: string;
  slug?: string | null;
  network: number | AffiliateNetwork;
  /**
   * Sites allowed to promote this offer (optional).
   */
  sites?: (number | Site)[] | null;
  status: 'draft' | 'active' | 'paused';
  externalId?: string | null;
  targetUrl?: string | null;
  commissionNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "click-events".
 */
export interface ClickEvent {
  id: number;
  tenant?: (number | null) | Tenant;
  occurredAt: string;
  eventType: 'click' | 'impression';
  site?: (number | null) | Site;
  offer?: (number | null) | Offer;
  destinationUrl?: string | null;
  referrer?: string | null;
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "commissions".
 */
export interface Commission {
  id: number;
  tenant?: (number | null) | Tenant;
  amount: number;
  currency: string;
  status: 'pending' | 'approved' | 'paid' | 'rejected';
  /**
   * Commission attributed to this system user (payout / team mapping).
   */
  recipient?: (number | null) | User;
  offer?: (number | null) | Offer;
  site?: (number | null) | Site;
  periodStart?: string | null;
  periodEnd?: string | null;
  paidAt?: string | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "knowledge-base".
 */
export interface KnowledgeBase {
  id: number;
  tenant?: (number | null) | Tenant;
  title: string;
  slug?: string | null;
  /**
   * Optional scope to one site.
   */
  site?: (number | null) | Site;
  categories?: (number | Category)[] | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  status: 'draft' | 'published' | 'archived';
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs".
 */
export interface AuditLog {
  id: number;
  tenant?: (number | null) | Tenant;
  action: string;
  collectionSlug?: string | null;
  documentId?: string | null;
  actor?: (number | null) | User;
  occurredAt: string;
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * API keys control which collections, resources, tools, and prompts MCP clients can access
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-mcp-api-keys".
 */
export interface PayloadMcpApiKey {
  id: number;
  /**
   * The user that the API key is associated with.
   */
  user: number | User;
  /**
   * A useful label for the API key.
   */
  label?: string | null;
  /**
   * The purpose of the API key.
   */
  description?: string | null;
  tenants?: {
    /**
     * Allow clients to find tenants.
     */
    find?: boolean | null;
    /**
     * Allow clients to create tenants.
     */
    create?: boolean | null;
    /**
     * Allow clients to update tenants.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete tenants.
     */
    delete?: boolean | null;
  };
  users?: {
    /**
     * Allow clients to find users.
     */
    find?: boolean | null;
    /**
     * Allow clients to create users.
     */
    create?: boolean | null;
    /**
     * Allow clients to update users.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete users.
     */
    delete?: boolean | null;
  };
  media?: {
    /**
     * Allow clients to find media.
     */
    find?: boolean | null;
    /**
     * Allow clients to create media.
     */
    create?: boolean | null;
    /**
     * Allow clients to update media.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete media.
     */
    delete?: boolean | null;
  };
  sites?: {
    /**
     * Allow clients to find sites.
     */
    find?: boolean | null;
    /**
     * Allow clients to create sites.
     */
    create?: boolean | null;
    /**
     * Allow clients to update sites.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete sites.
     */
    delete?: boolean | null;
  };
  affiliateNetworks?: {
    /**
     * Allow clients to find affiliate-networks.
     */
    find?: boolean | null;
    /**
     * Allow clients to create affiliate-networks.
     */
    create?: boolean | null;
    /**
     * Allow clients to update affiliate-networks.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete affiliate-networks.
     */
    delete?: boolean | null;
  };
  offers?: {
    /**
     * Allow clients to find offers.
     */
    find?: boolean | null;
    /**
     * Allow clients to create offers.
     */
    create?: boolean | null;
    /**
     * Allow clients to update offers.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete offers.
     */
    delete?: boolean | null;
  };
  categories?: {
    /**
     * Allow clients to find categories.
     */
    find?: boolean | null;
    /**
     * Allow clients to create categories.
     */
    create?: boolean | null;
    /**
     * Allow clients to update categories.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete categories.
     */
    delete?: boolean | null;
  };
  articles?: {
    /**
     * Allow clients to find articles.
     */
    find?: boolean | null;
    /**
     * Allow clients to create articles.
     */
    create?: boolean | null;
    /**
     * Allow clients to update articles.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete articles.
     */
    delete?: boolean | null;
  };
  pages?: {
    /**
     * Allow clients to find pages.
     */
    find?: boolean | null;
    /**
     * Allow clients to create pages.
     */
    create?: boolean | null;
    /**
     * Allow clients to update pages.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete pages.
     */
    delete?: boolean | null;
  };
  keywords?: {
    /**
     * Allow clients to find keywords.
     */
    find?: boolean | null;
    /**
     * Allow clients to create keywords.
     */
    create?: boolean | null;
    /**
     * Allow clients to update keywords.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete keywords.
     */
    delete?: boolean | null;
  };
  workflowJobs?: {
    /**
     * Allow clients to find workflow-jobs.
     */
    find?: boolean | null;
    /**
     * Allow clients to create workflow-jobs.
     */
    create?: boolean | null;
    /**
     * Allow clients to update workflow-jobs.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete workflow-jobs.
     */
    delete?: boolean | null;
  };
  knowledgeBase?: {
    /**
     * Allow clients to find knowledge-base.
     */
    find?: boolean | null;
    /**
     * Allow clients to create knowledge-base.
     */
    create?: boolean | null;
    /**
     * Allow clients to update knowledge-base.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete knowledge-base.
     */
    delete?: boolean | null;
  };
  rankings?: {
    /**
     * Allow clients to find rankings.
     */
    find?: boolean | null;
    /**
     * Allow clients to create rankings.
     */
    create?: boolean | null;
    /**
     * Allow clients to update rankings.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete rankings.
     */
    delete?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  collection: 'payload-mcp-api-keys';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'announcements';
        value: number | Announcement;
      } | null)
    | ({
        relationTo: 'sites';
        value: number | Site;
      } | null)
    | ({
        relationTo: 'site-blueprints';
        value: number | SiteBlueprint;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'social-platforms';
        value: number | SocialPlatform;
      } | null)
    | ({
        relationTo: 'social-accounts';
        value: number | SocialAccount;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'keywords';
        value: number | Keyword;
      } | null)
    | ({
        relationTo: 'rankings';
        value: number | Ranking;
      } | null)
    | ({
        relationTo: 'workflow-jobs';
        value: number | WorkflowJob;
      } | null)
    | ({
        relationTo: 'site-quotas';
        value: number | SiteQuota;
      } | null)
    | ({
        relationTo: 'affiliate-networks';
        value: number | AffiliateNetwork;
      } | null)
    | ({
        relationTo: 'offers';
        value: number | Offer;
      } | null)
    | ({
        relationTo: 'click-events';
        value: number | ClickEvent;
      } | null)
    | ({
        relationTo: 'commissions';
        value: number | Commission;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'knowledge-base';
        value: number | KnowledgeBase;
      } | null)
    | ({
        relationTo: 'audit-logs';
        value: number | AuditLog;
      } | null)
    | ({
        relationTo: 'tenants';
        value: number | Tenant;
      } | null)
    | ({
        relationTo: 'payload-mcp-api-keys';
        value: number | PayloadMcpApiKey;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'payload-mcp-api-keys';
        value: number | PayloadMcpApiKey;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'payload-mcp-api-keys';
        value: number | PayloadMcpApiKey;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "announcements_select".
 */
export interface AnnouncementsSelect<T extends boolean = true> {
  tenant?: T;
  kind?: T;
  teamLead?: T;
  author?: T;
  title?: T;
  body?: T;
  isActive?: T;
  isPinned?: T;
  startsAt?: T;
  endsAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sites_select".
 */
export interface SitesSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  slug?: T;
  primaryDomain?: T;
  status?: T;
  blueprint?: T;
  operators?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-blueprints_select".
 */
export interface SiteBlueprintsSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  slug?: T;
  description?: T;
  templateConfig?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  slug?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  slug?: T;
  site?: T;
  categories?: T;
  featuredImage?: T;
  body?: T;
  status?: T;
  publishedAt?: T;
  excerpt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  slug?: T;
  site?: T;
  categories?: T;
  featuredImage?: T;
  body?: T;
  status?: T;
  publishedAt?: T;
  excerpt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "social-platforms_select".
 */
export interface SocialPlatformsSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  slug?: T;
  status?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "social-accounts_select".
 */
export interface SocialAccountsSelect<T extends boolean = true> {
  tenant?: T;
  platform?: T;
  site?: T;
  handle?: T;
  status?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  tenant?: T;
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "keywords_select".
 */
export interface KeywordsSelect<T extends boolean = true> {
  tenant?: T;
  term?: T;
  slug?: T;
  site?: T;
  status?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rankings_select".
 */
export interface RankingsSelect<T extends boolean = true> {
  tenant?: T;
  keyword?: T;
  site?: T;
  searchQuery?: T;
  serpPosition?: T;
  serpUrl?: T;
  capturedAt?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "workflow-jobs_select".
 */
export interface WorkflowJobsSelect<T extends boolean = true> {
  tenant?: T;
  label?: T;
  jobType?: T;
  status?: T;
  site?: T;
  article?: T;
  page?: T;
  input?: T;
  output?: T;
  startedAt?: T;
  completedAt?: T;
  errorMessage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-quotas_select".
 */
export interface SiteQuotasSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  site?: T;
  maxPublishedPages?: T;
  maxMonthlyAiRuns?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "affiliate-networks_select".
 */
export interface AffiliateNetworksSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  slug?: T;
  websiteUrl?: T;
  status?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "offers_select".
 */
export interface OffersSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  slug?: T;
  network?: T;
  sites?: T;
  status?: T;
  externalId?: T;
  targetUrl?: T;
  commissionNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "click-events_select".
 */
export interface ClickEventsSelect<T extends boolean = true> {
  tenant?: T;
  occurredAt?: T;
  eventType?: T;
  site?: T;
  offer?: T;
  destinationUrl?: T;
  referrer?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "commissions_select".
 */
export interface CommissionsSelect<T extends boolean = true> {
  tenant?: T;
  amount?: T;
  currency?: T;
  status?: T;
  recipient?: T;
  offer?: T;
  site?: T;
  periodStart?: T;
  periodEnd?: T;
  paidAt?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  teamLead?: T;
  roles?: T;
  tenants?:
    | T
    | {
        tenant?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "knowledge-base_select".
 */
export interface KnowledgeBaseSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  slug?: T;
  site?: T;
  categories?: T;
  body?: T;
  status?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs_select".
 */
export interface AuditLogsSelect<T extends boolean = true> {
  tenant?: T;
  action?: T;
  collectionSlug?: T;
  documentId?: T;
  actor?: T;
  occurredAt?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants_select".
 */
export interface TenantsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  domain?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-mcp-api-keys_select".
 */
export interface PayloadMcpApiKeysSelect<T extends boolean = true> {
  user?: T;
  label?: T;
  description?: T;
  tenants?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  users?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  media?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  sites?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  affiliateNetworks?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  offers?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  categories?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  articles?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  pages?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  keywords?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  workflowJobs?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  knowledgeBase?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  rankings?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "commission-rules".
 */
export interface CommissionRule {
  id: number;
  /**
   * JSON for default splits, floors, approval policy, etc.
   */
  rules?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  notes?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quota-rules".
 */
export interface QuotaRule {
  id: number;
  /**
   * JSON for default per-site caps and tenant-wide limits.
   */
  rules?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  notes?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admin-branding".
 */
export interface AdminBranding {
  id: number;
  brandName?: string | null;
  logo?: (number | null) | Media;
  /**
   * e.g. #0f172a
   */
  primaryColor?: string | null;
  supportEmail?: string | null;
  notes?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "llm-prompts".
 */
export interface LlmPrompt {
  id: number;
  /**
   * Provider model id (e.g. gpt-4o-mini).
   */
  defaultModel?: string | null;
  temperature?: number | null;
  globalSystemPrompt?: string | null;
  apiNotes?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "prompt-library".
 */
export interface PromptLibrary {
  id: number;
  entries?:
    | {
        name: string;
        body: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "commission-rules_select".
 */
export interface CommissionRulesSelect<T extends boolean = true> {
  rules?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quota-rules_select".
 */
export interface QuotaRulesSelect<T extends boolean = true> {
  rules?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admin-branding_select".
 */
export interface AdminBrandingSelect<T extends boolean = true> {
  brandName?: T;
  logo?: T;
  primaryColor?: T;
  supportEmail?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "llm-prompts_select".
 */
export interface LlmPromptsSelect<T extends boolean = true> {
  defaultModel?: T;
  temperature?: T;
  globalSystemPrompt?: T;
  apiNotes?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "prompt-library_select".
 */
export interface PromptLibrarySelect<T extends boolean = true> {
  entries?:
    | T
    | {
        name?: T;
        body?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}